name: CD

on:
  workflow_dispatch:
    inputs:
      semver:
        required: true
        default: "1.9.3"
        type: string

permissions:
  contents: write

jobs:
  deploy:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:

      - name: Parse SemVer
        id: semver
        run: |
          VERSION="${{inputs.semver}}"
          VERSION="${VERSION#[vV]}"
          VERSION_MAJOR="${VERSION%%\.*}"
          VERSION_MINOR="${VERSION#*.}"
          VERSION_MINOR="${VERSION_MINOR%.*}"
          VERSION_PATCH="${VERSION##*.}"

          echo "Version: ${VERSION}"
          echo "Version [major]: ${VERSION_MAJOR}"
          echo "Version [minor]: ${VERSION_MINOR}"
          echo "Version [patch]: ${VERSION_PATCH}"
  
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "major=${VERSION_MAJOR}" >> "$GITHUB_OUTPUT"
          echo "minor=${VERSION_MINOR}" >> "$GITHUB_OUTPUT"
          echo "patch=${VERSION_PATCH}" >> "$GITHUB_OUTPUT"

      - name: Validate semver
        run: |
          pattern="^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[^+]+)?(?:\+[^+]+)?$"
          match=$SEMVER =~ $patern
          echo $match
          
          exit 1
        env:
          SEMVER: ${{steps.semver.outputs.version}}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit and push changes
        run: |
          git config user.name "${{github.event.actor.login}} <from-workflow-dispatch>"
          git config user.email github-actions@github.com
          echo Publishing ${{inputs.major}}.${{inputs.minor}}.${{inputs.patch}}
          
          sed -i 's/ARG RX_VERSION=.*/ARG RX_VERSION="${{steps.semver.outputs.major}}.${{steps.semver.outputs.minor}}.${{steps.semver.outputs.patch}}"/' Dockerfile
          
          git add Dockerfile
          git commit -m "Updating radix-cli to v${{steps.semver.outputs.major}}.${{steps.semver.outputs.minor}}.${{steps.semver.outputs.patch}}"
          git push
          git tag v${{steps.semver.outputs.major}}
          git tag v${{steps.semver.outputs.major}}.${{steps.semver.outputs.minor}}.${{steps.semver.outputs.patch}}
          git push origin v${{steps.semver.outputs.major}} --force
          git push origin v${{steps.semver.outputs.major}}.${{steps.semver.outputs.minor}}.${{steps.semver.outputs.patch}}
